name: Hardlands
version: '${version}'
main: team.heather.hardlands.Hardlands
description: A Paper plugin for hosting and managing UHC matches.
author: Pepe3012
website: https://github.com/TeamHeather/Hardlands
api-version: '26.2'
load: POSTWORLD

dependencies:
  server:
    Chunky:
      load: BEFORE
      required: true
      join-classpath: true

libraries:
  - com.google.code.gson:gson:2.14.0

permissions:
  hardlands.admin:
    description: Grants access to Hardlands administrative commands.
    default: op